import { writeActionData } from "./types";

export default [
  // TRANSFERS
  {
    type: "transfer",
    title: "shopping",
    icon: "HiShoppingBag",
    ammount: -80,
    currency: "EUR",
    frequency: null,
    other: "mall",
    description: "Clothing from seasonal sale",
    color: "#ff2d55",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "gifts",
    icon: "HiShoppingBag",
    ammount: -50,
    currency: "EUR",
    frequency: null,
    other: "friend",
    description: "Birthday present",
    color: "#5856d6",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "electronics",
    icon: "HiShoppingBag",
    ammount: -300,
    currency: "EUR",
    frequency: null,
    other: "Amazon",
    description: "New headphones",
    color: "#007aff",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "books",
    icon: "HiShoppingBag",
    ammount: -25,
    currency: "EUR",
    frequency: null,
    other: "Librarium",
    description: "Educational books",
    color: "#ff9500",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "coffee",
    icon: "HiShoppingBag",
    ammount: -12,
    currency: "EUR",
    frequency: null,
    other: "Starbucks",
    description: "Drinks with a friend",
    color: "#5ac8fa",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "Income",
    icon: "HiShoppingBag",
    ammount: 60,
    currency: "EUR",
    frequency: null,
    other: "Unknown",
    description: "One time income",
    color: "#4cd964",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "utilities",
    icon: "HiShoppingBag",
    ammount: -90,
    currency: "EUR",
    frequency: null,
    other: "ENEL",
    description: "Electricity bill",
    color: "#ff3b30",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "dining",
    icon: "HiShoppingBag",
    ammount: -45,
    currency: "EUR",
    frequency: null,
    other: "Restaurant",
    description: "Dinner out",
    color: "#ffcc00",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "phone bill",
    icon: "HiShoppingBag",
    ammount: -20,
    currency: "EUR",
    frequency: null,
    other: "Vodafone",
    description: "Monthly phone service",
    color: "#5ac8fa",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "groceries",
    icon: "HiShoppingBag",
    ammount: -65,
    currency: "EUR",
    frequency: null,
    other: "Mega Image",
    description: "Weekly groceries",
    color: "#34c759",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "transport",
    icon: "HiShoppingBag",
    ammount: -40,
    currency: "EUR",
    frequency: null,
    other: "Metrorex",
    description: "Monthly metro pass",
    color: "#007aff",
    sign: false,
    date: null,
  },
  {
    type: "transfer",
    title: "Transfer Template",
    icon: "HiOutlinePlus",
    ammount: -10,
    currency: "EUR",
    frequency: null,
    other: "Other",
    description: "Custom transfer",
    color: "#c7c7cc",
    sign: false,
    date: null,
  },

  // COMMITS
  {
    type: "commit",
    title: "freelancing",
    icon: "MdGroups",
    ammount: 700,
    currency: "EUR",
    frequency: 15,
    other: "Upwork",
    description: "Bi-weekly income",
    color: "#007aff",
    sign: true,
    date: null,
  },
  {
    type: "commit",
    title: "dividends",
    icon: "MdGroups",
    ammount: 50,
    currency: "EUR",
    frequency: 30,
    other: "Stocks",
    description: "Monthly stock dividends",
    color: "#5856d6",
    sign: true,
    date: null,
  },
  {
    type: "commit",
    title: "tutoring",
    icon: "MdGroups",
    ammount: 120,
    currency: "EUR",
    frequency: 7,
    other: "Student",
    description: "Weekly tutoring sessions",
    color: "#4cd964",
    sign: true,
    date: null,
  },
  {
    type: "commit",
    title: "rent income",
    icon: "MdGroups",
    ammount: 450,
    currency: "EUR",
    frequency: 30,
    other: "Tenant",
    description: "Monthly apartment rent",
    color: "#ff9500",
    sign: true,
    date: null,
  },
  {
    type: "commit",
    title: "scholarship",
    icon: "MdGroups",
    ammount: 200,
    currency: "EUR",
    frequency: 30,
    other: "University",
    description: "Education scholarship",
    color: "#ffcc00",
    sign: true,
    date: null,
  },
  {
    type: "commit",
    title: "part-time job",
    icon: "MdGroups",
    ammount: 300,
    currency: "EUR",
    frequency: 14,
    other: "Company X",
    description: "Weekend work",
    color: "#00c7be",
    sign: true,
    date: null,
  },
  {
    type: "commit",
    title: "loan payment",
    icon: "MdGroups",
    ammount: -300,
    currency: "EUR",
    frequency: 30,
    other: "Bank",
    description: "Loan installment",
    color: "#ff3b30",
    sign: false,
    date: null,
  },
  {
    type: "commit",
    title: "streaming",
    icon: "MdGroups",
    ammount: -15,
    currency: "EUR",
    frequency: 30,
    other: "Netflix",
    description: "Subscription fee",
    color: "#ff2d55",
    sign: false,
    date: null,
  },
  {
    type: "commit",
    title: "Commit Template",
    icon: "HiOutlinePlus",
    ammount: 0,
    currency: "EUR",
    frequency: 30,
    other: "Other",
    description: "Custom recurring transaction",
    color: "#c7c7cc",
    sign: true,
    date: null,
  },

  // GOALS (only positive)
  {
    type: "goal",
    title: "buy a car",
    icon: "GoGoal",
    ammount: 10000,
    currency: "EUR",
    frequency: null,
    other: null,
    description: "Save for a second-hand car",
    color: "#ff9500",
    sign: true,
    date: new Date("2026-01-01"),
  },
  {
    type: "goal",
    title: "house deposit",
    icon: "GoGoal",
    ammount: 25000,
    currency: "EUR",
    frequency: null,
    other: null,
    description: "Down payment for a house",
    color: "#ffcc00",
    sign: true,
    date: new Date("2025-07-01"),
  },
  {
    type: "goal",
    title: "education",
    icon: "GoGoal",
    ammount: 3000,
    currency: "EUR",
    frequency: null,
    other: null,
    description: "Courses for career growth",
    color: "#007aff",
    sign: true,
    date: new Date("2025-09-01"),
  },
  {
    type: "goal",
    title: "gift savings",
    icon: "GoGoal",
    ammount: 500,
    currency: "EUR",
    frequency: null,
    other: null,
    description: "Budget for yearly gifts",
    color: "#ff2d55",
    sign: true,
    date: new Date("2025-12-01"),
  },
  {
    type: "goal",
    title: "tech upgrade",
    icon: "GoGoal",
    ammount: 1500,
    currency: "EUR",
    frequency: null,
    other: null,
    description: "New laptop savings",
    color: "#5856d6",
    sign: true,
    date: new Date("2025-11-20"),
  },
  {
    type: "goal",
    title: "vacation",
    icon: "GoGoal",
    ammount: 1500,
    currency: "EUR",
    frequency: null,
    other: null,
    description: "Trip to Greece",
    color: "#5ac8fa",
    sign: true,
    date: new Date("2025-08-01"),
  },
  {
    type: "goal",
    title: "Goal Template",
    icon: "HiOutlinePlus",
    ammount: 0,
    currency: "EUR",
    frequency: null,
    other: null,
    description: "Custom goal",
    color: "#c7c7cc",
    sign: true,
    date: null,
  }
] as writeActionData[];
